/* Escreva defini¸c˜oes regulares para as seguintes linguagens:
(a) Todas as cadeias de letras min´usculas que contˆem as cinco vogais em ordem lexicogr´afica
crescente.
(b) Todas as cadeias de letras min´usculas em que as letras est˜ao em ordem lexicogr´afica crescente.
(c) Coment´arios, consistindo em uma cadeia delimitada por /∗ e ∗/, onde a cadeia de coment´arios pode ter qualquer sequˆencia de dig´ıtos, letras e um conjunto de operadores especiais: !, ], %, &.
(d) Todas as cadeias de a`s e b`s qu nao contem a subsequencia abb.*/
